trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: lint
  displayName: 'Lint'

  jobs:
  - job: 'lint'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self
      clean: true

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        architecture: 'x64'

    - script: |
        curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      displayName: 'Install pipenv'

    - script: |
        pipenv install --dev
      displayName: 'Install deps'

    - script: |
        make lint
      displayName: 'Run linters'

- stage: build
  displayName: 'Build docker image'

  jobs:
  - job: 'build'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self
      clean: true

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        architecture: 'x64'

    - script: |
        make build
      displayName: 'Build docker image'
