EXAMPLE_RESPONSE = {
    'entityUniqueId': 'DEEZER_SONG::411256382',
    'userCountry': 'RU',
    'pageUrl': 'https://song.link/d/411256382',
    'entitiesByUniqueId': {
        'DEEZER_SONG::411256382': {
            'id': '411256382',
            'type': 'song',
            'title': 'Aquila',
            'artistName': 'SubLab, Azaleh',
            'thumbnailUrl': 'https://cdns-images.dzcdn.net/images/cover/3354814c10e9f582c149e36b9cd2fd80/500x500-000000-80-0-0.jpg',
            'thumbnailWidth': 500,
            'thumbnailHeight': 500,
            'apiProvider': 'deezer',
            'platforms': ['deezer'],
        },
        'ITUNES_SONG::1289507580': {
            'id': '1289507580',
            'type': 'song',
            'title': 'Aquila',
            'artistName': 'Sublab & Azaleh',
            'thumbnailUrl': 'https://is1-ssl.mzstatic.com/image/thumb/Music118/v4/7d/6f/0f/7d6f0f60-cd35-9440-1d66-4a2cae1e8dc9/source/512x512bb.jpg',
            'thumbnailWidth': 512,
            'thumbnailHeight': 512,
            'apiProvider': 'itunes',
            'platforms': ['appleMusic', 'itunes'],
        },
        'SPOTIFY_SONG::5vBrvaXMQR30Kbp2q9J8ot': {
            'id': '5vBrvaXMQR30Kbp2q9J8ot',
            'type': 'song',
            'title': 'Aquila',
            'artistName': 'Sublab, Azaleh',
            'thumbnailUrl': 'https://i.scdn.co/image/ab67616d0000b273d2fdfa3bebbbdafe3e7b68be',
            'thumbnailWidth': 640,
            'thumbnailHeight': 640,
            'apiProvider': 'spotify',
            'platforms': ['spotify'],
        },
        'YOUTUBE_VIDEO::ZuqZ-PH5XPE': {
            'id': 'ZuqZ-PH5XPE',
            'type': 'song',
            'title': 'Sublab & ' 'Azaleh - ' 'Aquila',
            'artistName': 'Sublab',
            'thumbnailUrl': 'https://i.ytimg.com/vi/ZuqZ-PH5XPE/hqdefault.jpg',
            'thumbnailWidth': 480,
            'thumbnailHeight': 360,
            'apiProvider': 'youtube',
            'platforms': ['youtube', 'youtubeMusic'],
        },
        'GOOGLE_SONG::Thxgjrqy5rvu7wqdhfcyvfsnfxy': {
            'id': 'Thxgjrqy5rvu7wqdhfcyvfsnfxy',
            'type': 'song',
            'title': 'Aquila',
            'artistName': 'Sublab & Azaleh',
            'thumbnailUrl': 'https://lh3.googleusercontent.com/1Cl0PK-Dq3BupcmOrhee-VvLw2GqfsSb1OEvvDtu5nWNCLjAojI461ZsE4jJloqmjMmB7W_iZg',
            'thumbnailWidth': 512,
            'thumbnailHeight': 512,
            'apiProvider': 'google',
            'platforms': ['google', 'googleStore'],
        },
        'SOUNDCLOUD_SONG::344545599': {
            'id': '344545599',
            'type': 'song',
            'title': 'Sublab & ' 'Azaleh - ' 'Aquila',
            'artistName': 'Sublab',
            'thumbnailUrl': 'https://i1.sndcdn.com/artworks-000244822743-awitwq-t500x500.jpg',
            'thumbnailWidth': 500,
            'thumbnailHeight': 500,
            'apiProvider': 'soundcloud',
            'platforms': ['soundcloud'],
        },
        'AMAZON_SONG::B075XC4KNJ': {
            'id': 'B075XC4KNJ',
            'type': 'song',
            'title': 'Aquila',
            'artistName': 'Sublab & ' 'Azaleh',
            'thumbnailUrl': 'https://m.media-amazon.com/images/I/41LR3ZQ7XPL._AA500.jpg',
            'thumbnailWidth': 500,
            'thumbnailHeight': 500,
            'apiProvider': 'amazon',
            'platforms': ['amazonMusic', 'amazonStore'],
        },
        'TIDAL_SONG::79226043': {
            'id': '79226043',
            'type': 'song',
            'title': 'Aquila',
            'artistName': 'Sublab & Azaleh',
            'thumbnailUrl': 'https://resources.tidal.com/images/4e06ffe5/831b/452d/a032/facdf5c16a9c/640x640.jpg',
            'thumbnailWidth': 640,
            'thumbnailHeight': 640,
            'apiProvider': 'tidal',
            'platforms': ['tidal'],
        },
        'NAPSTER_SONG::tra.326812524': {
            'id': 'tra.326812524',
            'type': 'song',
            'title': 'Aquila',
            'artistName': 'SubLab',
            'thumbnailUrl': 'https://direct.rhapsody.com/imageserver/images/alb.326812523/385x385.jpeg',
            'thumbnailWidth': 385,
            'thumbnailHeight': 385,
            'apiProvider': 'napster',
            'platforms': ['napster'],
        },
    },
    'linksByPlatform': {
        'deezer': {
            'url': 'https://www.deezer.com/track/411256382',
            'entityUniqueId': 'DEEZER_SONG::411256382',
        },
        'appleMusic': {
            'url': 'https://geo.music.apple.com/ru/album/_/1289507575?i=1289507580&mt=1&app=music&at=1000lHKX',
            'nativeAppUriMobile': 'music://itunes.apple.com/ru/album/_/1289507575?i=1289507580&mt=1&app=music&at=1000lHKX',
            'nativeAppUriDesktop': 'itmss://itunes.apple.com/ru/album/_/1289507575?i=1289507580&mt=1&app=music&at=1000lHKX',
            'entityUniqueId': 'ITUNES_SONG::1289507580',
        },
        'spotify': {
            'url': 'https://open.spotify.com/track/5vBrvaXMQR30Kbp2q9J8ot',
            'nativeAppUriDesktop': 'spotify:track:5vBrvaXMQR30Kbp2q9J8ot',
            'entityUniqueId': 'SPOTIFY_SONG::5vBrvaXMQR30Kbp2q9J8ot',
        },
        'youtube': {
            'url': 'https://www.youtube.com/watch?v=ZuqZ-PH5XPE',
            'entityUniqueId': 'YOUTUBE_VIDEO::ZuqZ-PH5XPE',
        },
        'youtubeMusic': {
            'url': 'https://music.youtube.com/watch?v=ZuqZ-PH5XPE',
            'entityUniqueId': 'YOUTUBE_VIDEO::ZuqZ-PH5XPE',
        },
        'google': {
            'url': 'https://play.google.com/music/m/Thxgjrqy5rvu7wqdhfcyvfsnfxy?signup_if_needed=1',
            'entityUniqueId': 'GOOGLE_SONG::Thxgjrqy5rvu7wqdhfcyvfsnfxy',
        },
        'soundcloud': {
            'url': 'https://soundcloud.com/sublabmusic/aquila',
            'entityUniqueId': 'SOUNDCLOUD_SONG::344545599',
        },
        'amazonMusic': {
            'url': 'https://music.amazon.com/albums/B075XF7X34?trackAsin=B075XC4KNJ&do=play',
            'entityUniqueId': 'AMAZON_SONG::B075XC4KNJ',
        },
        'tidal': {
            'url': 'https://listen.tidal.com/track/79226043',
            'entityUniqueId': 'TIDAL_SONG::79226043',
        },
        'napster': {
            'url': 'http://napster.com/artist/art.23948599/album/alb.326812523/track/tra.326812524',
            'entityUniqueId': 'NAPSTER_SONG::tra.326812524',
        },
        'itunes': {
            'url': 'https://geo.music.apple.com/ru/album/_/1289507575?i=1289507580&mt=1&app=itunes&at=1000lHKX',
            'nativeAppUriMobile': 'itmss://itunes.apple.com/ru/album/_/1289507575?i=1289507580&mt=1&app=itunes&at=1000lHKX',
            'nativeAppUriDesktop': 'itmss://itunes.apple.com/ru/album/_/1289507575?i=1289507580&mt=1&app=itunes&at=1000lHKX',
            'entityUniqueId': 'ITUNES_SONG::1289507580',
        },
        'googleStore': {
            'url': 'https://play.google.com/store/music/album?id=Bpgsbok76p4ohqb2xx7pfbko4wu&tid=song-Thxgjrqy5rvu7wqdhfcyvfsnfxy',
            'entityUniqueId': 'GOOGLE_SONG::Thxgjrqy5rvu7wqdhfcyvfsnfxy',
        },
        'amazonStore': {
            'url': 'https://amazon.com/dp/B075XC4KNJ?tag=songlink0d-20',
            'entityUniqueId': 'AMAZON_SONG::B075XC4KNJ',
        },
    },
}
