stages:
- stage: lint
  displayName: 'Lint'

  jobs:
  - job: 'lint'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self
      clean: true

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        architecture: 'x64'

    - script: |
        pip install poetry
      displayName: 'Install poetry'

    - script: |
        poetry install
      displayName: 'Install deps'

    - script: |
        make lint
      displayName: 'Run linters'
