stages:
  - stage: publish
    displayName: 'Publish'
    condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'tags'))

    jobs:
      - job: 'Publish'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.8'
              architecture: 'x64'

          - script: |
              pip install poetry
            displayName: 'Install poetry'
          - script: |
              poetry config repositories.pypi https://test.pypi.org/legacy/
            displayName: 'Config repo'
          - script: |
              poetry publish --build
            displayName: 'Publish to PyPI'
            env:
              POETRY_PYPI_TOKEN_PYPI: $(PYPI_TOKEN)
